[package]
name = "lightcore"
version = "0.1.0"
authors = ["tiannian <dtiannian@aliyun.com>"]
edition = "2018"

[dependencies]
void = "1.0.2"
tokio = "0.1.22"
tokio-io = "0.1.12"
libp2p = "0.11.0"
libp2p-tcp = "0.11.0"
futures = "0.1.28"
env_logger = "0.6.2"
